# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Test Site
tagline:          None
url:              http://robrothedev.github.io
paginate:         1
baseurl:          /
author:
  name:           Mark Otto
  url:            https://twitter.com/mdo
  email:          markdotto@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole
