# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Rob Rothe
tagline:          PHP // AngularJS // UI Web Developer
url:              http://robrothedev.github.io
paginate:         1
baseurl:          http://robrothedev.github.io/
author:
  name:           Rob Rothe
  url:            https://twitter.com/robrothedev
  email:          robrothe@gmail.com
