# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Rob Rothe // PHP, AngularJS and UI Web Developer
tagline:          None
url:              http://robrothedev.github.io
paginate:         1
baseurl:          http://robrothedev.github.io/
author:
  name:           Rob Rothe
  url:            https://twitter.com/robrothedev
  email:          robrothe@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole
